### ISSUE TITLE
[Submission] Local Battery Plugin

### ISSUE THREAD

**Issue by pacjo** [KieronQuinn/SmartspacerPluginRepository#24]
### Package Name

nodomain.pacjo.smartspacer.plugin.localbattery

### Name

Local Battery

### Author

pacjo

### Description

Allows you to see current battery level and remaining charging time when connected to power

### Plugin URL

https://raw.githubusercontent.com/pacjo/SmartspacerPlugins/main/app/src/localbattery/plugin.json

### Code of Conduct

- [X] I agree to follow this repository's Code of Conduct

**Comment by KieronQuinn** [comment]
The action to validate the plugins isn't firing, I'll fix it shortly then it can be approved
